-- AlterTable
ALTER TABLE "Partners" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isArchive" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "updateUser" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE "Partners" ADD CONSTRAINT "Partners_updateUser_fkey" FOREIGN KEY ("updateUser") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
